import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {setTimeout as delay} from 'node:timers/promises';import {Store} from '../src/store.mjs';import {Engine} from '../src/engine.mjs';
async function fixture(execute){const dir=await mkdtemp(join(tmpdir(),'workflow-test-'));const store=new Store(dir);const engine=new Engine(store,{workspace:dir,execute,runTimeoutMs:10000});return {engine,store,start:async r=>{const draft=await engine.start(r);return draft.status==='pending_review'?engine.approve(draft.id,{revision:draft.revision}):draft;},cleanup:async()=>{await engine.close();store.close();await rm(dir,{recursive:true,force:true});}};}
async function done(e,id){for(let i=0;i<300;i++){const s=e.snapshot(id);if(!e.active.has(id))return s;await delay(20);}throw Error('test timeout');}
const request=(script,extra={})=>({requestId:'r1',name:'测试',executor:'demo',script,input:{},...extra});
test('parallel execution is bounded, outputs persisted, start idempotent',async()=>{let active=0,max=0,calls=0;const f=await fixture(async(s,{signal})=>{calls++;max=Math.max(max,++active);await delay(50,undefined,{signal});active--;return {output:{id:s.id}};});try{const r=await f.start(request(`return await ctx.map([1,2,3,4],i=>ctx.agent({id:'a'+i,prompt:'test'}));`,{concurrency:2}));assert.equal((await f.start(request(r.script,{concurrency:2}))).id,r.id);const out=await done(f.engine,r.id);assert.equal(out.status,'succeeded');assert.equal(calls,4);assert.equal(max,2);assert.equal(out.steps.length,4);await assert.rejects(f.start(request('return 2')),/requestId/);}finally{await f.cleanup();}});
test('resume reuses successful steps and retains failed results',async()=>{let calls=[];let fail=true;const f=await fixture(async s=>{calls.push(s.id);if(s.id==='b'&&fail)throw Error('transient');return {output:s.id};});try{const r=await f.start(request(`const a=await ctx.agent({id:'a',prompt:'a'});const b=await ctx.agent({id:'b',prompt:'b',dependsOn:['a']});return {a,b};`));let out=await done(f.engine,r.id);assert.equal(out.status,'completed_with_gaps');fail=false;await f.engine.resume(r.id);out=await done(f.engine,r.id);assert.equal(out.status,'succeeded');assert.deepEqual(calls,['a','b','b']);}finally{await f.cleanup();}});
test('cancel aborts in-flight work and does not dispatch queued calls',async()=>{let calls=0;const f=await fixture(async(s,{signal})=>{calls++;await delay(3000,undefined,{signal});return {output:null};});try{const r=await f.start(request(`return await ctx.map([1,2,3],i=>ctx.agent({id:'s'+i,prompt:'p'}));`,{concurrency:1}));while(calls===0)await delay(10);await f.engine.stop(r.id);assert.equal(calls,1);assert.equal(f.engine.snapshot(r.id).status,'cancelled');assert.equal(f.engine.slots,0);}finally{await f.cleanup();}});
test('invalid schema result is a failure, not success',async()=>{const f=await fixture(async()=>({output:{a:1}}));try{const r=await f.start(request(`return await ctx.agent({id:'a',prompt:'p',schema:{type:'string'}});`));const out=await done(f.engine,r.id);assert.equal(out.status,'completed_with_gaps');assert.equal(out.steps[0].status,'failed');}finally{await f.cleanup();}});
test('script loops are interrupted, no modules or node globals',async()=>{const f=await fixture();try{await assert.rejects(f.start(request(`await import('node:fs')`)));const r=await f.start(request('while(true) {}'));const out=await done(f.engine,r.id);assert.equal(out.status,'failed');}finally{await f.cleanup();}});
test('call budgets are enforced even with a map',async()=>{const f=await fixture(async()=>({output:null}));try{const r=await f.start(request(`return await ctx.map([1,2,3],i=>ctx.agent({id:'a'+i,prompt:'p'}))`,{maxCalls:2}));const out=await done(f.engine,r.id);assert.equal(out.status,'failed');assert.equal(out.attempts,2);}finally{await f.cleanup();}});
test('simultaneous starts cannot exceed workflow capacity',async()=>{const f=await fixture(async(s,{signal})=>{await delay(2000,undefined,{signal});return {output:null};});try{const results=await Promise.allSettled(Array.from({length:6},(_,i)=>f.start(request('return await ctx.agent({id:"a",prompt:"p"});',{requestId:'capacity'+i}))));assert.equal(results.filter(r=>r.status==='fulfilled').length,3);assert.equal(f.engine.active.size,3);}finally{await f.cleanup();}});
test('simultaneous resumes launch only one replay',async()=>{const f=await fixture(async(s,{signal})=>{await delay(2000,undefined,{signal});return {output:null};});try{const run=await f.start(request('return await ctx.agent({id:"a",prompt:"p"});'));await f.engine.stop(run.id,'paused');const results=await Promise.allSettled([f.engine.resume(run.id),f.engine.resume(run.id)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);}finally{await f.cleanup();}});
test('configured budgets reach executor, persist, and change only on explicit resume',async()=>{
 const seen=[];let fail=true;const f=await fixture(async(s,o)=>{seen.push({id:s.id,maxSteps:o.maxSteps,timeoutMs:o.timeoutMs});if(s.id==='b'&&fail)throw Object.assign(Error('limited'),{details:{code:'AGENT_STEP_LIMIT',message:'limited'}});return {output:s.id};});
 try{const r=await f.start(request('const a=await ctx.agent({id:"a",prompt:"a"});const b=await ctx.agent({id:"b",prompt:"b",dependsOn:["a"]});return {a,b}',{maxSteps:75,stepTimeoutMs:240000,runTimeoutMs:900000,maxCalls:2}));await done(f.engine,r.id);assert.equal(f.engine.snapshot(r.id).steps[1].errorDetails.code,'AGENT_STEP_LIMIT');fail=false;await f.engine.resume(r.id,{maxSteps:180,stepTimeoutMs:1800000,runTimeoutMs:7200000,maxCalls:5});const end=await done(f.engine,r.id);assert.equal(end.status,'succeeded');assert.deepEqual(seen,[{id:'a',maxSteps:75,timeoutMs:240000},{id:'b',maxSteps:75,timeoutMs:240000},{id:'b',maxSteps:180,timeoutMs:1800000}]);assert.equal(end.steps[0].maxSteps,75);assert.equal(end.steps[1].maxSteps,180);assert.equal(end.steps[1].attempt,2);assert.equal(end.maxCalls,5);}finally{await f.cleanup();}
});
test('new defaults are 120 steps and 30 minutes; invalid budgets fail before dispatch',async()=>{const f=await fixture(async()=>({output:null}));try{const r=await f.start(request('return 1'));assert.equal(r.maxSteps,120);assert.equal(r.stepTimeoutMs,1800000);for(const change of [{maxSteps:0},{maxSteps:1.5},{maxSteps:1001},{stepTimeoutMs:null},{stepTimeoutMs:999},{runTimeoutMs:86400001}])await assert.rejects(f.start(request('return 1',{requestId:JSON.stringify(change),...change})),/整数/);}finally{await f.cleanup();}});
test('legacy limits are presented as historical values and old idempotent requests still work',async()=>{
 const f=await fixture();try{const {hash}=await import('../src/common.mjs');const original={name:'旧版',script:'return 1',input:{},executor:'demo',concurrency:2,maxCalls:20};f.store.save({id:'legacy',requestId:'legacy-r',requestHash:hash(original),...original,status:'failed',attempts:1,workspace:f.engine.options.workspace,fingerprints:{},phases:[]});f.store.saveStep('legacy',{id:'a',kind:'agent',status:'failed',error:'MCode limit_exceeded'});const s=f.engine.snapshot('legacy');assert.equal(s.maxSteps,30);assert.equal(s.stepTimeoutMs,600000);assert.equal(s.legacyLimits,true);assert.match(s.steps[0].error,/30 步/);assert.equal(f.store.step('legacy','a').error,'MCode limit_exceeded');const changed=f.store.get('legacy');changed.maxSteps=120;changed.stepTimeoutMs=1800000;f.store.save(changed);assert.equal(f.engine.snapshot('legacy').steps[0].maxSteps,30);assert.match(f.engine.snapshot('legacy').steps[0].error,/30 步/);delete changed.maxSteps;delete changed.stepTimeoutMs;f.store.save(changed);assert.equal((await f.start({requestId:'legacy-r',...original})).id,'legacy');}finally{await f.cleanup();}
});
test('workflow timeout has a distinct cause and cancels the active executor',async()=>{const f=await fixture(async(s,{signal})=>{await delay(5000,undefined,{signal});return {output:null};});try{const r=await f.start(request('return await ctx.agent({id:"a",prompt:"p"});',{runTimeoutMs:1000}));const end=await done(f.engine,r.id);assert.equal(end.status,'failed');assert.equal(end.errorDetails.code,'WORKFLOW_TIMEOUT');assert.equal(end.steps[0].errorDetails.code,'WORKFLOW_TIMEOUT');assert.match(end.error,/1 秒/);}finally{await f.cleanup();}});
test('missing MCode is rejected on approval without dispatch',async()=>{const f=await fixture();f.engine.options.command=join(f.engine.options.workspace,'missing-mcode');try{await assert.rejects(f.start(request('return 1',{executor:'mcode'})),/找不到 MCode CLI/);assert.equal(f.store.list().length,1);assert.equal(f.store.list()[0].status,'pending_review');assert.equal(f.store.list()[0].attempts,0);}finally{await f.cleanup();}});
test('schema decoding preserves raw text and returns validated fields to downstream steps',async()=>{
 const raw='```json\n{"selected":{"name":"Example"}}\n```';let calls=0;
 const f=await fixture(async()=>{calls++;return {output:raw};});
 try{const r=await f.start(request(`const a=await ctx.agent({id:'a',prompt:'p',schema:{type:'object',required:['selected'],properties:{selected:{type:'object',required:['name'],properties:{name:{type:'string'}}}}}});if(a.status!=='succeeded')return {gap:a.error};return a.output.selected.name;`));const end=await done(f.engine,r.id);assert.equal(end.status,'succeeded');assert.equal(end.result,'Example');assert.equal(end.steps[0].rawOutput,raw);assert.equal(end.steps[0].outputFormat,'json_fence');assert.equal(calls,1);}finally{await f.cleanup();}
});
test('invalid structured output is retained on the failed producer; guarded scripts finish with gaps and resume retries it',async()=>{
 let good=false,calls=0;const raw='## 研究文档（引用来源参考）\n(no reference document available)';
 const f=await fixture(async()=>{calls++;return {output:good?'{"selected":{"name":"Example"}}':raw,sessionId:'session',turnId:'turn'};});
 try{const r=await f.start(request(`const a=await ctx.agent({id:'a',prompt:'p',schema:{type:'object',required:['selected'],properties:{selected:{type:'object',required:['name'],properties:{name:{type:'string'}}}}}});if(a.status!=='succeeded')return {gaps:[a.errorDetails]};return a.output.selected.name;`));let end=await done(f.engine,r.id);assert.equal(end.status,'completed_with_gaps');assert.equal(end.steps[0].status,'failed');assert.equal(end.steps[0].rawOutput,raw);assert.equal(end.steps[0].output,null);assert.equal(end.steps[0].sessionId,'session');assert.equal(end.result.gaps[0].code,'OUTPUT_SCHEMA_INVALID');assert.equal(calls,1);good=true;await f.engine.resume(r.id);end=await done(f.engine,r.id);assert.equal(end.result,'Example');assert.equal(calls,2);}finally{await f.cleanup();}
});
test('without a schema, narrative output remains unparsed',async()=>{
 const raw='{"name":"report"}',f=await fixture(async()=>({output:raw}));try{const r=await f.start(request('return await ctx.agent({id:"a",prompt:"p"});'));const end=await done(f.engine,r.id);assert.equal(end.result.output,raw);assert.equal(end.steps[0].rawOutput,undefined);}finally{await f.cleanup();}
});
test('uncertain cleanup requires explicit confirmation and cannot be resumed or repaired directly',async()=>{
 let calls=0;const f=await fixture(async(s,{signal})=>{calls++;try{await delay(3000,undefined,{signal});}catch{}throw Object.assign(Error('tree cleanup unconfirmed'),{details:{code:'MCODE_CLEANUP_UNCONFIRMED',message:'tree cleanup unconfirmed'}});});
 try{
  const r=await f.start(request('return await ctx.map([1,2,3],i=>ctx.agent({id:"a"+i,prompt:"p"}));',{concurrency:1}));
  while(!calls)await delay(10);
  const end=await f.engine.stop(r.id,'paused');
  assert.equal(end.status,'needs_attention');assert.equal(end.errorDetails.code,'MCODE_CLEANUP_UNCONFIRMED');assert.equal(calls,1);
  assert.equal(end.steps.find(s=>s.id==='a1').errorDetails.code,'MCODE_CLEANUP_UNCONFIRMED');
  await assert.rejects(f.engine.resume(r.id),/确认旧 Agent/);
  await assert.rejects(f.engine.repair(r.id,{script:'return 1'}),/确认旧 Agent/);
 }finally{await f.cleanup();}
});
