import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {messages,resolveLanguage,normalizePreference,readPreference,savePreference,translate,describeFailure} from '../web/i18n.mjs';
test('system language handles Chinese variants and uses English for other primary languages',()=>{for(const lang of ['zh-CN','zh-TW','zh-Hant-HK','zh'])assert.equal(resolveLanguage('auto',[lang]),'zh');for(const langs of [['en-US'],['fr-FR','zh-CN'],[]])assert.equal(resolveLanguage('auto',langs),'en');assert.equal(resolveLanguage('en',['zh-CN']),'en');assert.equal(resolveLanguage('zh',['en-US']),'zh');assert.equal(normalizePreference('invalid'),'auto');});
test('explicit preference persists; blocked storage falls back without breaking UI',()=>{let value;const storage={setItem:(k,v)=>value=v,getItem:()=>value};savePreference(storage,'en');assert.equal(readPreference(storage),'en');savePreference(storage,'auto');assert.equal(readPreference(storage),'auto');const blocked={getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}};assert.equal(readPreference(blocked),'auto');assert.doesNotThrow(()=>savePreference(blocked,'zh'));});
test('both dictionaries cover identical keys, placeholders and all static page labels',async()=>{assert.deepEqual(Object.keys(messages.en).sort(),Object.keys(messages.zh).sort());for(const key of Object.keys(messages.en)){const vars=s=>(s.match(/\{\w+\}/g)??[]).sort();assert.deepEqual(vars(messages.en[key]),vars(messages.zh[key]),key);}const html=await readFile('web/index.html','utf8');for(const [,key]of html.matchAll(/data-i18n(?:-aria|-title)?="([^"]+)"/g))assert.ok(messages.en[key],key);assert.equal(translate('en','minutes',{count:30}),'30 min');});
test('structured failures localize actual limits without altering raw diagnostics',()=>{const f={code:'AGENT_STEP_LIMIT',maxSteps:30,message:'达到上限',cause:'provider: 额度耗尽'};const result=describeFailure('en',f);assert.match(result.title,/30-step/);assert.equal(result.original,f.cause);assert.equal(describeFailure('zh',f).title,f.message);assert.match(describeFailure('en',{code:'AGENT_TIMEOUT',timeoutMs:1800000}).title,/30-minute/);assert.match(describeFailure('en',{code:'WORKFLOW_TIMEOUT',runTimeoutMs:7200000}).title,/120-minute/);assert.equal(describeFailure('en',{},'未知错误').original,'未知错误');assert.equal(describeFailure('en',{code:'MCODE_START_FAILED',message:'ENOENT：启动失败'}).original,'ENOENT：启动失败');});
test('null error details from healthy and queued nodes never crash the inspector',()=>{
 for(const language of ['en','zh'])for(const failure of [null,undefined,{}])assert.doesNotThrow(()=>describeFailure(language,failure,null));
});
