import test from 'node:test';import assert from 'node:assert/strict';
import {readableHTML,readableMarkdown,readingValue,rawText,markdownText,codeFence} from '../web/readable.mjs';
import {exportReport,reportModel} from '../src/reports.mjs';
test('JSON string and JSON fence outputs become readable without changing original content',()=>{const value='{"coverageGaps":["No tests"],"projectFound":true}';assert.deepEqual(readingValue(value),{coverageGaps:['No tests'],projectFound:true});assert.equal(rawText(value),value);assert.match(readableHTML(value,{language:'en'}),/Coverage gaps/);assert.match(readableHTML('```json\n'+value+'\n```',{language:'zh'}),/覆盖缺口/);assert.equal(readingValue('before '+value),'before '+value);assert.match(readableHTML('[1,2]'),/<ol/);});
test('Markdown headings, tables, lists, code and links render and export without flattened lines',()=>{const text='# Result\n\n**Verified**\n\n- first\n- second\n\n| Area | State |\n| --- | --- |\n| API | Ready |\n\n```js\nconst x = 1;\n```\n\n[Source](https://example.com)';const html=readableHTML(text);for(const pattern of [/<h2>Result/,/<strong>Verified/,/<table>/,/<li>first/,/<pre><code class="language-js">/,/href="https:\/\/example.com/])assert.match(html,pattern);const md=readableMarkdown(text);assert.match(md,/### Result\n/);assert.match(md,/\n- first\n- second/);assert.match(md,/\n\| Area \| State \|/);assert.match(md,/```js\nconst x = 1;/);});
test('untrusted output cannot inject active HTML, dangerous URLs or remote images',()=>{for(const value of ['<script>alert(1)</script>','<img src=x onerror=alert(1)>','[click](javascript:alert%281%29)','[click](data:text/html,evil)','[click](jav&#x61;script:alert%281%29)','![remote](https://example.com/tracker.png)','<iframe src="https://example.com"></iframe>']){const html=readableHTML(value);assert.doesNotMatch(html,/<script|<img|<iframe|href="(?:javascript|data):/i);assert.doesNotMatch(markdownText(value),/<script|<img|<iframe|\]\((?:javascript|data):/i);}const html=readableHTML({['<script>']:'safe',url:'https://example.com/?a=1&b=2'});assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script/);});
test('raw JSON appendix remains valid JSON even with HTML and fence characters',()=>{const value={text:'<script>\n```\n& entities'};const fenced=codeFence(value),body=fenced.split('\n').slice(1,-1).join('\n');assert.deepEqual(JSON.parse(body),value);assert.doesNotMatch(fenced,/<script/);});
const run={id:'report-test',name:'Reading report',status:'succeeded',executor:'mcode',attempts:1,revision:1,metadata:{objective:'Review'},result:{conclusion:'# Findings\n\n**Good**\n\n| A | B |\n| --- | --- |\n| 1 | 2 |',raw:{huge:'original evidence'}}};const steps=[{kind:'agent',id:'a',label:'Audit',status:'succeeded',output:'{"summary":"A useful result"}'}];
test('aggregate conclusion leads, duplicate raw data becomes an appendix, and node evidence is retained',()=>{const model=reportModel(run,steps);assert.equal(model.hasAppendix,true);assert.equal(model.result.raw,undefined);assert.ok(run.result.raw);const html=exportReport(run,steps).body;assert.ok(html.indexOf('id="conclusions"')<html.indexOf('id="records"'));assert.match(html,/<details class="record"/);assert.match(html,/id="original"/);assert.match(html,/<strong>Good<\/strong>/);assert.match(html,/A useful result/);assert.match(html,/Content-Security-Policy/);const md=exportReport(run,steps,{format:'md'}).body;assert.match(md,/\n\| A \| B \|/);assert.match(md,/Original aggregate data/);assert.ok(md.includes('original evidence'));});
test('planned unexecuted nodes are part of report coverage, not silently dropped',()=>{const r={...run,status:'failed',error:'Failure',topology:{nodes:[{id:'p1',stepId:'a',label:'Audit',kind:'agent',dependsOn:[]},{id:'p2',stepId:'b',label:'Report',kind:'agent',dependsOn:['p1']}],edges:[],phases:[]}};const model=reportModel(r,steps);assert.equal(model.known.length,2);assert.equal(model.gaps.length,1);assert.match(exportReport(r,steps).body,/1\/2 agents succeeded/);assert.match(exportReport(r,steps,{format:'md'}).body,/Coverage gaps/);});

test('heading rebasing leaves fenced source and repeated headings intact',()=>{const value='# A\n\n# A\n\n```md\n# A\n```';const result=readableMarkdown(value);assert.equal((result.match(/^### A$/gm)??[]).length,2);assert.match(result,/```md\n# A\n```/);});

test('Markdown export preserves comparison operators inside source code',()=>{const text='Use `a < b && c > d`.\n\n```js\nif (a < b) return "<safe>";\n```';assert.equal(readableMarkdown(text),text);});
